// <auto-generated />
using System;
using LoiterScan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoiterScan.Data.Migrations
{
    [DbContext(typeof(LoiterScanDbContext))]
    partial class LoiterScanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("LoiterScan.Data.Entities.CatalogGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("NoradId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NoradId", "GroupName")
                        .IsUnique();

                    b.ToTable("catalog_groups", (string)null);
                });

            modelBuilder.Entity("LoiterScan.Data.Entities.CatalogObjectEntity", b =>
                {
                    b.Property<long>("NoradId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ApogeeKm")
                        .HasColumnType("REAL");

                    b.Property<double>("ArgPerigeeDeg")
                        .HasColumnType("REAL");

                    b.Property<double>("BStar")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("DecayDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Eccentricity")
                        .HasColumnType("REAL");

                    b.Property<int>("EphemerisType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EpochAgeDays")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("EpochUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("InclinationDeg")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntlDesignator")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDebris")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MeanAnomalyDeg")
                        .HasColumnType("REAL");

                    b.Property<double>("MeanMotionDdotRevPerDay")
                        .HasColumnType("REAL");

                    b.Property<double>("MeanMotionDotRevPerDay")
                        .HasColumnType("REAL");

                    b.Property<double>("MeanMotionRevPerDay")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<double>("PerigeeKm")
                        .HasColumnType("REAL");

                    b.Property<double>("RaanDeg")
                        .HasColumnType("REAL");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SemiMajorAxisKm")
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NoradId");

                    b.ToTable("catalog_objects", (string)null);
                });

            modelBuilder.Entity("LoiterScan.Data.Entities.ConfigParamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcquisitionSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialUsername")
                        .HasColumnType("TEXT");

                    b.Property<int>("CoarseStepMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CoarseThresholdKm")
                        .HasColumnType("REAL");

                    b.Property<int>("CoarseToFineMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DetectionStepMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DetectionThresholdKm")
                        .HasColumnType("REAL");

                    b.Property<bool>("ExcludeDebris")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExcludeGroupPairsOnly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FineStepMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FineThresholdKm")
                        .HasColumnType("REAL");

                    b.Property<int>("FineToDetectionMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HorizonDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoiterExcursionAllowanceMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoiterMinDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxEpochAgeDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RefreshBeforeRun")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegimeScope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("config_params", (string)null);
                });

            modelBuilder.Entity("LoiterScan.Data.Entities.ExclCountryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Country")
                        .IsUnique();

                    b.ToTable("excl_countries", (string)null);
                });

            modelBuilder.Entity("LoiterScan.Data.Entities.ExclGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupName")
                        .IsUnique();

                    b.ToTable("excl_groups", (string)null);
                });

            modelBuilder.Entity("LoiterScan.Data.Entities.ExclIdEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("NoradId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NoradId")
                        .IsUnique();

                    b.ToTable("excl_ids", (string)null);
                });

            modelBuilder.Entity("LoiterScan.Data.Entities.ExclPairEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("PairKeyHigh")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PairKeyLow")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PairKeyLow", "PairKeyHigh")
                        .IsUnique()
                        .HasDatabaseName("ix_excl_pairs_pair_key");

                    b.ToTable("excl_pairs", (string)null);
                });

            modelBuilder.Entity("LoiterScan.Data.Entities.LoiteringEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CloseApproachUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<double>("DurationMinutes")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LoiterEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoiterStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("MinRangeKm")
                        .HasColumnType("REAL");

                    b.Property<string>("NameA")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameB")
                        .HasColumnType("TEXT");

                    b.Property<long>("NoradIdA")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NoradIdB")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PairIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PairKeyHigh")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PairKeyLow")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("PairKeyLow", "PairKeyHigh")
                        .HasDatabaseName("ix_event_pair_key");

                    b.ToTable("loitering_events", (string)null);
                });

            modelBuilder.Entity("LoiterScan.Data.Entities.RunEntity", b =>
                {
                    b.Property<long>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CatalogEpochWindowEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CatalogEpochWindowStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventsDetected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalPairsChecked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("RunId");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("LoiterScan.Data.Entities.CatalogGroupEntity", b =>
                {
                    b.HasOne("LoiterScan.Data.Entities.CatalogObjectEntity", "CatalogObject")
                        .WithMany("Groups")
                        .HasForeignKey("NoradId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogObject");
                });

            modelBuilder.Entity("LoiterScan.Data.Entities.LoiteringEventEntity", b =>
                {
                    b.HasOne("LoiterScan.Data.Entities.RunEntity", "Run")
                        .WithMany("Events")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("LoiterScan.Data.Entities.CatalogObjectEntity", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("LoiterScan.Data.Entities.RunEntity", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
